### ISSUE TITLE
Trigger click on toolbar

### ISSUE THREAD

**Issue by return-none** [Leaflet/Leaflet.draw#179]
Is it possible to emulate click on component(eg. Poliline/Marker) to enable this mode using js?

**Comment by sensejus** [comment]
Maybe for someone this solution will help to save a lot of time. I was banging my head for long time to accomplish this simple solution. The problem was then I was trying to trigger polyline drawing by using examples provided here and in other pages, the actions toolbar was not showing in draw menu ('Cancel drawing' and 'Delete last point' buttons ) so my solution was to trigger mouse click event on Draw polyline button and here is how I have accomplished this:

var event = document.createEvent('Event');
                event.initEvent('click', true, true);
                var cb = document.getElementsByClassName('leaflet-draw-draw-polyline');
                !cb[0].dispatchEvent(event);

This is not nice solution, but I was unable to find better one , and also this works cross-browser

**Comment by sythel** [comment]
@sensejus thanks dude

**Comment by torfsen** [comment]
For reference, here's what I'm using to fake a click on the rectangle button in the draw toolbar in version 0.3.2:
```
myDrawControl._toolbars.draw._modes.rectangle.handler.enable()
```

**Comment by ivan-bilan** [comment]
@kiprasbal, your solution works best!

**Comment by Alexan7892** [comment]
As @gushiguera  and @paranoicsan wrote:
$('.leaflet-draw-edit-edit').click()  and $('.leaflet-draw-edit-edit').click()  doesn't work, 
but 
$('.leaflet-draw-edit-edit')[0].click() and $('.leaflet-draw-edit-edit')[0].click() should work correctly.
