### ISSUE TITLE
Fixed position of tooltip

### ISSUE THREAD

**Issue by smeijer** [Leaflet/Leaflet.draw#335]
Would be nice if we could fix the position of the tooltip.

In my opinion the mouse following technique is pretty annoying. I can see why someone likes it, but when drawing some more detailed sketches, its just getting in the way.

Sticking the tooltip to the top or bottom off the map, makes it more draw-friendly. As far as I know, this can't be overridden by css currently, because of the dynamically applied `transform`.

**Comment by Candyffm** [comment]
Although this issue is pretty old, I felt the same way. This is my workaround:
In the css look for .leaflet-draw-tooltip and add the following properties:
```
margin-left : 0;
margin-top : 0;
top : 10px; // adjust to your needs
left : 20px; // adjust to your needs
transform : none!important;
```

this removes the tooltip completely (display: none is sufficient for that). The transform property makes sure the tooltip doesn't follow the cursor. As the tooltip wrapper has no width or height you are stuck with positioning the tooltip relative to the top left corner, unless you are okay with adding some JS.

I have positioned the tooltip to the top center. In this case add these lines to leaflet-draw-tooltip:
```
margin-left : 0;
margin-top : 0;
display : none;
top : 10px;
transform : translateX(-50%)!important;
```

We need display display: none to avoid any jumping of the tooltip. Depending on your scenario you might want to remove the tooltip triangle. Just comment out .leaflet-draw-tooltip:before and your done.

Then add the following event listener to your map:
```
map.on('draw:toolbaropened', function (e) {
    setTimeout(function(){
        $('.leaflet-draw-tooltip').css({left: $mapWrapper.width()/2, display: 'block'});
    })
});
```

Replace $mapWrapper with a Jquery selected element that represents the dimensions of your map. setTimeout is needed as the tooltip might with a slight delay. In this case $('.leaflet-draw-tooltip') is not able to select the tooltip DOM.

With these all tooltips are centered. If you strive for perfection, you might want to adjust the position of the tooltip when the user resizes the browser window. In this case add the following snippet:
```
$(window).on('resize', function(){
     setTimeout(function(){
         $('.leaflet-draw-tooltip').css({left: $mapWrapper.width()/2, display: 'block'});
     })
});
```
