### ISSUE TITLE
Possible to Use Drawing Functions Without the Control?

### ISSUE THREAD

**Issue by FunkMonkey33** [Leaflet/Leaflet.draw#53]
Hi,

Thanks for an awesome plugin.

Is it possible to, say, draw a rectangle without using the drawing control?  We use our own controls to interact with the Leaflet map, and want to implement our own drawing toolbar.  

For example, when you click the rectangle button in your implementation, the L.Handler.Draw.enable method is called, which looks like this:

enable: function() {
    this.fire('activated');
    this._map.fire('drawing', {drawingType: this.type});
    L.Handler.prototype.enable.call(this);
}

I can already raise the map.drawing event, because I store a reference to the map.  The this.fire() method is a little trickier, though.  I assume the 'this' is a reference to the L.Handler.Draw object, so I'll need a reference to this object to call it from another class.  Is it possible to get a reference to the current L.Handler.Draw object?

Thanks!

Aaron

**Comment by chander** [comment]
Sorry, is there a reason why you can't just do this:

L.DomUtil.addClass(drawControl.getContainer(), 'hide')

To hide the toolbar on the map?  Then you can use the control externally (as noted above) without it being map-visible.

**Comment by calebmelies** [comment]
Hello everyone,

I am trying to use this plugin along with the leaflet snap plugin.  I have successfully added the drawControl outside of the map using something like:

----------------------------------------------------------------------------
var drawControl = new L.Control.Draw({
  draw: { 
	  polyline: true,
	  polygon: true,
	  rectangle: false,
	  circle: false,
	  marker: true
	},
	//position: 'topleft',
});
----------------------------------------------------------------------------

This is working great, however it is not allowing for the new drawing to snap to the defined 'guidelayers' because the setDrawingOptions method will not bind to the drawControl I am building.

Have there been any updates that might be useful to mine/other's situations similar to this?
