### ISSUE TITLE
Lealfet 1.0.0 Support - Editing/deleting doesn't work

### ISSUE THREAD

**Issue by gholol** [Leaflet/Leaflet.draw#553]
Should I still use the Leaflet-master branch for 1.0.0? Because I'm experiencing some problems with it.
the Leaflet-master branch seems to be stale as the last update was made 6 months ago... (!) It's kinda confusing. 

I'm using Leaflet 1.0.0-rc1. 
I can succesfully draw features and they are added to the map, however, once they are added, I cannot edit/delete them as modify/delete buttons are grayed out.  No errors are given.

Here's my code:

        // Initialise the FeatureGroup to store editable layers
        let drawnItems = new L.FeatureGroup();
        this._map.addLayer(drawnItems);

        // Initialise the draw control and pass it the FeatureGroup of editable layers
        let drawControl = new L.Control.Draw({
            draw: {
              polyline: {
                  metric: true
              },
              polygon: {
                  allowIntersection: false,
                  showArea: true,
                  drawError: {
                    color: '#b00b00',
                    timeout: 1000
                  },
                  shapeOptions: {
                    color: '#bada55'
                  }
              },
              marker: false
            },
            edit: {
              featureGroup: drawnItems
            }
        });
        this._map.addControl(drawControl);

        // Listen for editor events
        this._map.on('draw:created', (e) => {
          let type = e.layerType,
              layer = e.layer;

            this._map.addLayer(layer);
        });

I also cannot remove the last point of the polyline.

**Comment by ddproxy** [comment]
I apologize for the confusion, Leaflet.Draw has not been updated for 1.0 support yet, however it is planned.

**Comment by gholol** [comment]
Oh, thanks for the info. Hopefully it'll be added soon

**Comment by kozze89** [comment]
@ddproxy Is there a branch, an issue or something to follow to see the progress of this work?

**Comment by chugcup** [comment]
@gholol I think your problem is that you have to add editable items to the `drawnItems` layer.  That can be fixed in your 'draw:created'  handler.

    // Listen for editor events
    this._map.on('draw:created', (e) => {
      let type = e.layerType,
          layer = e.layer;

        drawnItems.addLayer(layer);
    });

I ran into the same problem when I started.

That doesn't mean editing works in 1.0.0 though... you will still run into issues once the buttons become clickable :-(

**Comment by gholol** [comment]
@chugcup Hello Jeff, IIRC they are added in the option object

`        edit: {
          featureGroup: drawnItems
        }` 

Anyway, I managed to get it to work with leaflet 1.0.
Well, kinda... I ditched the original controls entirely and went with using handlers directly.

**Comment by chugcup** [comment]
Assigning `{ featureGroup: drawnItems }` only tells Leaflet.draw which layer to watch when its determining if there are any items to edit/delete.  There's a method here:

https://github.com/Leaflet/Leaflet.draw/blob/master/src/edit/EditToolbar.js#L121

that is triggered when layers are added/removed to that `featureGroup`.  You can see it checks if any layers exist in this `featureGroup`; this determines if the buttons are enabled/disabled.

Placing your drawn layers in this feature group allows you to do things like hide all drawn items by simply removing the `drawnItems` layer.  Otherwise you would have to keep track of all those layers and remove them one-by-one.
